package:
  name: landlab
  version: "0.1.38"

source:
  git_url: https://github.com/landlab/landlab
  git_rev: v0.1.38

requirements:
  build:
    - python
    - scipy
    - numpy
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - sympy
    - pandas
    - cython
    - six
    - setuptools

  run:
    - python
    - scipy
    - numpy
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - sympy
    - pandas
    - cython
    - six
    - setuptools
